stages:
  - package-release

package-release:
  image: node:12.17.0
  stage: package-release
  before_script:
    - git remote set-url origin https://gitlab-ci-token:$CI_PUSH_TOKEN@$CI_SERVER_HOST/$CI_PROJECT_PATH.git
    - git config --global user.email 'gabriel.mule@cyberlabs.ai'
    - git config --global user.name 'gitlab-ci'
    - |
        {
          echo "registry=https://registry.npmjs.org/"
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN"
        } | tee --append .npmrc
  script:
    - node "./ci.js" $CI_COMMIT_TAG
    - npm ci
    - npm run build
    - npm publish --access public
  after_script:
    - git checkout -B master
    - git add package.json
    - git commit -m '[gitlab-ci] Published Version'
    - git push "https://gitlab-ci-token:$CI_PUSH_TOKEN@$CI_SERVER_HOST/$CI_PROJECT_PATH.git"
    - git tag -d $CI_COMMIT_TAG
    - git tag $CI_COMMIT_TAG
    - git push "https://gitlab-ci-token:$CI_PUSH_TOKEN@$CI_SERVER_HOST/$CI_PROJECT_PATH.git" --tags --force
  rules:
    - if: '$CI_COMMIT_TITLE == "[gitlab-ci] Published Version"'
      when: never
    - if: '$CI_COMMIT_TAG =~ /^release-/'
      when: always
    - when: never
  tags:
    - gitlab-org
